name: Go
on: [push, pull_request]
env:
  QUAY_PATH: quay.io/brancz/kube-rbac-proxy
  kind-version: 'v0.25.0'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-go
  cancel-in-progress: true

jobs:
  check-license:
    runs-on: ubuntu-latest
    name: Check license
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check license
      run: make check-license

  generate:
    runs-on: ubuntu-latest
    name: Generate
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Golang Environment
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Generate
      run: make generate && git diff --exit-code

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Lint Go
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout=5m

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Golang Environment
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Build
      run: make build

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Golang Environment
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Run unit tests
      run: make test-unit

  e2e-tests:
    runs-on: ubuntu-latest
    name: E2E tests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Golang Environment
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Start kind & create cluster
      uses: engineerd/setup-kind@v0.6.2
      with:
        version: ${{ env.kind-version }}
        config: test/e2e/kind-config/kind-config.yaml
        wait: 300s

    - name: Wait for cluster to finish bootstraping
      run: kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s

    - name: Create container & run tests
      run: |
        VERSION=local VERSION_SEMVER=$(cat ./VERSION) make container
        kind load docker-image ${QUAY_PATH}:local
        until docker exec $(kind get nodes) crictl images | grep "${QUAY_PATH}"; do
          echo "no kube-rbac-proxy image"
          sleep 1
        done
        make test-e2e

  publish:
    runs-on: ubuntu-latest
    name: Publish container image to Quay
    if: github.event_name == 'push'
    needs:
    - check-license
    - generate
    - build
    - unit-tests
    - e2e-tests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Golang Environment
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build images and push
      run: ./scripts/publish.sh
