name: Create release (GHCR)

on:
  push:
    tags:
      - 'v*'

permissions: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  go-version: 1.26.2

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish container image to ghcr.io
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
        persist-credentials: false

    - name: Setup Golang Environment
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ env.go-version }}
        cache: false

    - name: Login to ghcr.io
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build images and push
      env:
        REGISTRY_PATH: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      run: ./scripts/publish.sh
